guillotinaweb/ngx-schema-form

Readme.md
I review the [readme.md](readme.md) file.
I hope it is clearer, let me know if it looks good.
I had [an example](https://github.com/makinacorpus/angular2-schema-form/pull/11/files#diff-1e290ac8433d555bce009b162cb869d0R143) to help readers understand what we mean.
=> review readme.md

README.md, src/model/formproperty.ts
Support visibleIf condition that show/hide the target field depending if the source field has any value
=> support-any-value-dep

src/widgetchooser.component.ts
+ Update WidgetChooser to redraw views on schema change
+ Fix issue(https://github.com/makinacorpus/angular2-schema-form/issues/85)
=> Re-render View on Schema Config Change

src/form.component.ts
+ Add logic to check existence of property `schema` before accessing `schema.type`
=> Fix Component crash when input schema is not defined or null 

src/model/formpropertyfactory.ts
Fixes issue #83 (visibleIf inside array). 
Implements the suggested fix by artonio.
=> Fix error where visibleif was not working in arrays #83

src/widget.ts
Broken TSC compilation process due to @angular/forms API change (@anuglar/forms/src/model.d.ts#setErrors)
=> Update Code due to @angular/forms API change

src/model/formproperty.ts
Added evaluation of the required state of a property.
This allows easily to set a required mark to corresponding component.
Would be glad to see this coming
-------
**Example of showing asterisk as mark for required fields**
=> Required state for FormProperty

README.md, src/defaultwidgets/button/button.widget.ts
AOT compatibility restored
Some properties had to be made public in order to be fully AOT compatible
=> enhanced AOT compatibility with custom rendered buttons

src/defaultwidgets/defaultwidgetregistry.ts, src/index.ts
ButtonWidget was not exported.
=> Fix export for ButtonWidget.

src/form.component.ts
Minor changes on the FormComponent:
`(isValid)="isValid = $event"` boolean value, form is valid or not
`(onErrorChange)="errors = $event.value"` lists schema validation errors
=> isValid and onErrorChange event emitters added

src/widget.ts
Issue: https://github.com/makinacorpus/angular2-schema-form/issues/131
=> ArrayLayoutWidget, ObjectLayoutWidget implements AfterViewInit interface

src/model/schemapreprocessor.ts
Fixing this issue: https://github.com/makinacorpus/angular2-schema-form/issues/135
Sorry about this issue. Object type self-referencing $ref-s cause infinite loop, they should remove from schema at preprocess time.
Like this one below. #/definitions/item/bar/thing property will suppressed.
```
{
type: 'object',
properties: {
thing: {
$ref: '#/definitions/item'
},
},
definitions: {
item: {
type: 'object',
properties: {
foo: {
type: 'string'
},
bar: {
type: 'object',
properties: {
baz: {
type: 'integer'
},
thing: {
$ref: '#/definitions/item'
}
}
}
}
}
}
}
```
=> self-referencing object properties should remove

README.md
Fixing the missing and wrong path to the demo lib directory
=> Fixing symbolic link in demo project

src/form.component.ts
Implementation of #77. Nothing happened on that issue, so I implemented it myself.
It exposes an EventEmittor that emits the Errors of the root.
=> This implements issue #77 (Validity of the form is not exposed in any way.)

src/defaultwidgets/select/select.widget.ts, tests/src/app/app.component.html, tests/src/app/app.component.ts, tests/src/app/samplemodel.json, tests/src/app/sampleschema.json
Works with the same schema approach as `checkbox`.
E.g
```js
"category": {
"description": "Category",
"type":"array",
"widget": "select",
"items" : {
"type": "string",
"oneOf": [
{"description": "Design","enum": ["design"]},
{"description": "High-Tech","enum": ["hightech"]},
{"description": "Materials","enum": ["materials"]},
{"description": "Services","enum": ["services"]}
]
}
}
``` 
Also updated schema example to show usecase.
=> Added support for multiple select. Closes #151

src/terminator.service.ts
rxjs/Rx should not be imported anymore
=> For Angular5 and Typescript 2.4.2

src/form.component.ts
=> add model two way binding

.gitignore, CHANGELOG.md, package.json, src/defaultwidgets/defaultwidgetregistry.ts, src/model/formproperty.spec.ts, src/widgetchooser.component.spec.ts, tests/.angular-cli.json, tests/package.json, tests/src/app/app.component.ts, tests/src/app/app.module.ts, tests/src/tsconfig.app.json, tests/src/tsconfig.spec.json, tests/src/typings.d.ts, tests/tsconfig.json
=> Make tests run ng cli 1.5

README.md, tests/src/app/app.module.ts
Updated Test app
Update README
=> fixes #180

src/schema-form.module.ts
update module in order to define a static declaration
=> fix aot compilation

src/schemavalidatorfactory.ts
This PR should fix issue #201.
=> Fixed "deep" validation, fix #201.

package.json, projects/schema-form/package.json, projects/schema-form/src/lib/model/formproperty.ts, projects/schema-form/src/lib/terminator.service.ts
=> Remove rxjs-compat

src/app/json-schema-example/json-schema-example.component.ts
Fixed demo page first schema (for master)
=> fixed demo page first schema

projects/schema-form/src/lib/defaultwidgets/array/array.widget.ts, projects/schema-form/src/lib/model/arrayproperty.ts, src/app/json-schema-example/sampleschema.json
=> fix array item remove

projects/schema-form/src/lib/schemavalidatorfactory.ts
=> Reset SchemaValidator

package-lock.json, projects/schema-form/src/lib/defaultwidgets/string/string.widget.ts, projects/schema-form/src/lib/model/schemapreprocessor.ts
=> Renamed the `required` flag, fixed #263.

projects/schema-form/src/lib/defaultwidgets/select/select.widget.ts
=> Issue #287: Select is not disabled in readOnly mode

package-lock.json, projects/schema-form/src/lib/defaultwidgets/_directives/disableControl.directive.ts, projects/schema-form/src/lib/defaultwidgets/index.ts, projects/schema-form/src/lib/defaultwidgets/select/select.widget.ts, projects/schema-form/src/lib/index.ts, projects/schema-form/src/lib/schema-form.module.ts, projects/schema-form/src/public_api.ts, src/app/json-schema-example/json-schema-example.component.ts, src/app/json-schema-example/sampleschema.json
As recommended in this angular issue: https://github.com/angular/angular/issues/11271,
the select widget uses a directive to reliable set the disabled state.
=> fix disabled state for reactive forms by using directive. fix #287

CHANGELOG.md, projects/schema-form/package.json, projects/schema-form/src/public_api.ts
Need more models available via Public API. Particularly, right now I need ObjectProperty to provide my own implementation of widgets layer.
=> Update Public API

CHANGELOG.md, projects/schema-form/package.json, projects/schema-form/src/lib/model/formproperty.ts
Allow visible if to work with numeric values
=> VisibleIf  numeric support

projects/schema-form/package.json, projects/schema-form/src/lib/form.component.ts, projects/schema-form/src/lib/formelement.component.ts, projects/schema-form/src/lib/log.service.ts, projects/schema-form/src/lib/model/arrayproperty.ts, projects/schema-form/src/lib/model/atomicproperties.spec.ts, projects/schema-form/src/lib/model/booleanproperty.ts, projects/schema-form/src/lib/model/formproperty.spec.ts, projects/schema-form/src/lib/model/formproperty.ts, projects/schema-form/src/lib/model/formpropertyfactory.ts, projects/schema-form/src/lib/model/numberproperty.ts, projects/schema-form/src/lib/model/objectproperty.spec.ts, projects/schema-form/src/lib/model/objectproperty.ts, projects/schema-form/src/lib/model/stringproperty.ts, projects/schema-form/src/lib/schema-form.module.ts
Implemented a basic version of a logging service to handle console logs.
For Version 2.4.x
=> Fix 343 2.4.x

CHANGELOG.md, README.md, projects/schema-form/package.json, projects/schema-form/src/lib/model/formproperty.ts, src/app/json-schema-example/json-schema-example.component.ts, src/app/json-schema-example/visibility-binding-example-schema2.json
Fixed issues 
#360 
#331 
#329
=> 2.4.8 fix 360 331 329

CHANGELOG.md, README.md, package.json, projects/schema-form/package.json, projects/schema-form/src/lib/model/formproperty.ts, src/app/json-schema-example/json-schema-example.component.spec.ts, src/app/json-schema-example/json-schema-example.component.ts, src/app/json-schema-example/json-schema-example.component.visibleIf.spec.ts, src/app/json-schema-example/visibility-binding-example-schema2.json, src/app/template-schema-example/template-schema-example.component.html, src/app/template-schema-example/template-schema-example.component.spec.ts, src/app/template-schema-example/template-schema-example.component.ts
Fixed issues 
#360 
#331 
#329
=> Fix 360 331 329

CHANGELOG.md, package-lock.json, projects/schema-form/package.json, projects/schema-form/src/lib/model/formproperty.ts, src/app/json-schema-example/json-schema-example.component.visibleIf.spec.ts, src/app/json-schema-example/visibility-binding-example-schema2.json
Also adds support for having '$EXP$'  conditions summed up in an array.
=> fix #367 - Fix boolean negative visiblityIf condition.

projects/schema-form/src/lib/model/formproperty.ts
=> #386 fix for visibleIf using wildcards in oneOf and allOf

projects/schema-form/src/lib/model/ISchema.ts, projects/schema-form/src/lib/model/atomicproperties.spec.ts, projects/schema-form/src/lib/model/formproperty.ts, projects/schema-form/src/lib/model/formpropertyfactory.ts, projects/schema-form/src/lib/model/index.ts, projects/schema-form/src/lib/model/nullproperty.ts, projects/schema-form/src/lib/model/stringproperty.ts, projects/schema-form/src/lib/model/utils.ts, projects/schema-form/src/lib/template-schema/field/field-parent.ts, projects/schema-form/src/lib/template-schema/field/field.component.ts, projects/schema-form/src/lib/template-schema/field/field.ts, projects/schema-form/src/public_api.ts
=> Remove constraint of using nullable unions

projects/schema-form/src/lib/model/formproperty.ts, src/app/json-schema-example/visibility-binding-example-schema2.json
=> #414 fixes validation of ANY to validate more types of values

projects/schema-form/src/lib/schemavalidatorfactory.ts
Included the recommendation from https://github.com/guillotinaweb/ngx-schema-form/issues/319#issuecomment-589224451 as part of the specifcation of the `SchemaValidatorFactory`.
=> Built-in ability to let compile the schema so defs and refs get resolved

projects/schema-form/src/lib/model/formproperty.ts
I seperate the pull requests because they do not belong together.
Here is the fix for the wildcard bug I introduced myself with version 2.8.2
=> Fixed bug with wildcards introduced by version 2.8.2

CHANGELOG.md, package-lock.json, package.json, projects/schema-form/package.json, projects/schema-form/src/lib/model/formproperty.spec.ts, projects/schema-form/src/lib/template-schema/field/field.component.ts
=> Upgrade to Angular 16

CHANGELOG.md, projects/schema-form/package.json
=> version 2.10.1
