guillotinaweb/ngx-schema-form

- src/schema-form/schema-form.module.ts
As stated in #26 , a feature module should only import CommonModule and not the whole BrowserModule which belong to only the main App module of a web application
> fix#26 - Replace BrowserModule by CommonModule

- README.md
`<schema-form>` is used in the docs; however, `<sf-form>` is actually what is registered for the component.
> fix tag used in docs

- README.md
- package.json
- tsconfig.json
I found the package [npm-install-peers](https://github.com/spatie/npm-install-peers) which relies on the  peerDependencies located in the package.json (whereas `npm info` looks at the peerDependencies in the npm registry, which are not always up to date with the git repository).
@ebrehault, @SBats, if you think it is not relevant, do not hesitate to close this PR.
I also added   ` "@angular/forms": "^2.4.0" ` which is required for building.
> Added a command to package.json to install peer dependencies.

- README.md
- src/model/formproperty.ts
This hides widgets with a visibleIf field with an empty Object like:
"registerNewsletter": {
"type": "boolean",
"description": "I want to receive the newsletter",
"default": false,
"visibleIf": { }
}
As discussed in Issue #102 
I also added an example to the readme. This might be a bit overkill. 
Also this change should be tested as it has the potential to break some peoples forms if I made a mistake. I don't have enough test examples.
> hidden empty visibleIfs 

- src/index.ts
- src/schema-form.module.ts
- src/schemavalidatorfactory.ts
This PR adds support to provide custom `SchemaValidatorFactory`.
At the same time, I've added `SchemaFormModule.forRoot()` wich returns module with default providers (providing both WidgetFactory and SchemaValidatorFactory)
> Allow providing SchemaValidatorFactory

- package.json
- src/defaultwidgets/object/object.widget.ts
- src/model/schemapreprocessor.ts
Two main changes were made
The object widget now has a description title. 
The title properties then goes for the legend element. 
The _fieldset_ created within the object widget 
did contain the _description_ of the json schema element as a legend but not the _title_.
So when in json schema element both properties, _title_ and _description_, where set,
then only the description were visible.
Also the _name_ property of the schema element will be passed to the fieldset instance,
but it will not be rendered into the template.
To make the project work with angular version ^4.0.3 zone had to be updated.
would be glad to see this coming
> Updated Object Widget Description Property. Angular Version, Zone.js

- README.md
- src/defaultwidgets/string/string.widget.ts
Support for INPUT TYPE HIDDEN.
This pull request solves the lack of hidden fields that are bound to the output model.
In contrast to the conditional field visibility via the `visibleIf` condition, 
which removes the field properties from the output model,
the use of the `widget.id` `hidden` with a default value will keep the field property in the output model. 
would be glad to see this coming
> added support for hidden field by using widget id 'hidden'

- README.md
- src/defaultwidgets/button/button.widget.ts
- src/defaultwidgets/index.ts
- src/formelement.action.component.ts
- src/formelement.component.ts
- src/index.ts
- src/schema-form.module.ts
The `WidgetRegistry` now can also create the buttons for the schema actions.
This allows to keep the buttons in the same style as the other widget (Bootstrap, Material ...etc).
Since I couldn't see any obvious reason to create an extra registry I did extend the `DefaultWidgetRegistry` to provide also the button-widgets.
Would be glad to see this coming
--------
**Example image of custom rendered action buttons**
> enabled custom rendering of schema action buttons

- src/schema-form.module.ts
```
imports: [
...
SchemaFormModule.forRoot([
{
provide: SchemaValidatorFactory,
useClass: AjvValidatorFactory
}
]),
...
]
```
> forRoot() now able to change default providers

- src/form.component.ts
- src/model/arrayproperty.ts
- src/model/atomicproperties.spec.ts
- src/model/atomicproperty.ts
- src/model/booleanproperty.ts
- src/model/formproperty.ts
- src/model/numberproperty.ts
- src/model/objectproperty.ts
- src/model/schemapreprocessor.ts
- src/schema-form.module.ts
- src/schemavalidatorfactory.ts
- src/widget.ts
On the result object the properties appears when it's value is other than fallback value.
Why?
This is expected due to the JSON schema required property validation. If the result object properties fills out with fallback values we lost the ability to check the property is present (required) or not.
Example of its earlier operation:
```
const schema = {
"type": "object",
"required": ["foo"],
"properties": {
"foo": {
"type": "string"
}
}
}
```
```
const result = {
foo: ""
}
```
In  this case the result object is valid. The only thing what we can do to prevent submit the empty form is  to supplement the schema with "minLength": 1
The expected result in the example above is:
```
const result = {}
```
In this case the validator will warn you of the missing (required) property. Object is going …
> Result object reduced only to visible and dirty properties

- src/model/formpropertyfactory.ts
- src/model/schemapreprocessor.ts
- src/schemavalidatorfactory.ts
Sadly remote schema definitions not supported yet but static defintions works well. Recursive, self-referencing definitions too.
Example:
```
{
type: 'object',
properties: {
name: {
$ref: '#/definitions/stringProp'
},
something: {
type: 'array',
items: {
type: 'object',
properties: {
name: {
$ref: '#/definitions/stringProp'
}
}
}
},
nodes: {
type: 'array',
items: {
$ref: '#/definitions/nodeItem'
}
}
},
definitions: {
stringProp: {
type: 'string',
minLength: 3
},
nodeItem: {
type: 'object',
properties: {
name: {
$ref: '#/definitions/stringProp'
},
nodes: {
type: 'array',
items: {
$ref: '#/definitions/nodeItem'
}
}
}
}
}
}
```
> deep $ref support for definitions

- tests/tslint.json
rxjs/Rx should not be imported anymore
> For Angular5 and Typescript 2.4.2

- src/form.component.ts
Allow providing SchemaValidatorFactory 2 - FormComponent
The provided `SchemaValidatorFactory` via the module providers is not being used in FormComponent,
since the `SchemaValidatorFactory` is explicitly set to `ZSchemaValidatorFactory`.
To make it work, the declaration of the SchemaValidatorFactory must be removed from the providers, since it is already declared as global provider in `schema-form.module.ts`.
> fixes #173

- CHANGELOG.md
- src/form.component.ts
As mentioned by @GFoley83, the suffix must be `Change` not `Changed` (see https://angular-2-training-book.rangle.io/handout/components/app_structure/two_way_data_binding.html)
> rename modelChanged to modelChange

- projects/schema-form/src/lib/form.component.ts
- projects/schema-form/src/lib/formelement.component.ts
- projects/schema-form/src/lib/schema-form.module.ts
- projects/schema-form/src/lib/widget.ts
- projects/schema-form/src/public_api.ts
ng-packagr is having problems (dherges/ng-packagr#917 , angular/angular-cli#10967) with index imports inside the library after build. Importing directly from the definition is a workaround to the problem.
resolve #210.
> Replaced index imports with direct ones

- projects/schema-form/src/lib/index.ts
- projects/schema-form/src/public_api.ts
add Action, ActionRegistry and ValidatorRegistry to public api
I would recommend to extend the public API with the classes `Action`, `ActionRegistry` and `ValidatorRegistry`.
I've the case where it is required to execute an action from action-registry even if it is not bound to any button.
```
const action: Action = this.actionRegistry.get(actionId)
if (action) {
action(this.formProperty, params)
}
```
The same for validator-registry.
_would be happy to see this coming :-)_
> add Action, ActionRegistry and ValidatorRegistry to public api - fixes #228

- projects/schema-form/src/lib/model/schemapreprocessor.ts
This pull request allows flexible alternate names for the three known JSON schema extensions of `ngx-schema-form`.
| Name | Regular Expression | Examples
| ---- | ---- | ---- |
| fieldsets  | `/^x-?field-?sets$/i` | `X-Field-Sets`, `x-fieldsets`, `xFieldSets` |
| widget | `/^x-?widget$/i` | `X-Widget`, `x-widget`, `xWidget` |
| visibleIf | `/^x-?visible-?if$/i` | `X-Visible-If`, `x-visbleif`, `xVisibleIf` |
----
I tested...
```
function normalizeExtensions(schema) {
const extensions = [
{ name: "fieldsets", regex: /^x-?field-?sets$/i },
{ name: "widget",    regex: /^x-?widget$/i },
{ name: "visibleIf", regex: /^x-?visible-?if$/i }
];
const keys = Object.keys(schema);
for (let i = 0; i < keys.length; ++i) {
let k = keys[i];
let e = extensions.find(e => !!k.match(e.regex));
if (e) {
let v = …
```
> Add normalizeExtensions to SchemaPreprocessor

- README.md
- package.json
- schema/ngx-schema-form-schema.json
I'd like to share this JSON Schema file that helps me a lot.
It is just a handy helper  for your IDE when creating schema forms.
Simply set it in the`$schema` property in the `.json` file and the IDE's autocompletion does the rest.
Here a GIF image that shows what it looks like with IntelliJ:
If there is a chance to get this schema on a public domain, this would be also a greater benefit.
Any way I would love to see this coming.
> add json schema declaring schema-form specific properties

- projects/schema-form/src/lib/defaultwidgets/checkbox/checkbox.widget.ts
- projects/schema-form/src/lib/defaultwidgets/radio/radio.widget.ts
- projects/schema-form/src/lib/defaultwidgets/range/range.widget.ts
- projects/schema-form/src/lib/defaultwidgets/select/select.widget.ts
- projects/schema-form/src/lib/defaultwidgets/textarea/textarea.widget.ts
I conditionally set and unset the readOnly property (true/false) and have been running into some issues where the read only property doesn't seem to be unsetting. 
I think it might be because `[attr.readonly]="schema.readOnly"` will set the readonly property when schema.readOnly = false. Here's a [stackOverflow post](https://stackoverflow.com/questions/45226354/conditionally-make-input-field-readonly-in-angular-2-or-4-advice-best-which-w) about it as well. It should be: [readonly]="schema.readOnly" unless there is a specific reason `[attr.readonly]` is needed?
I guess the alternative is what I've seen used in the default string widget: 
`[attr.readonly]="(schema.widget.id!=='color') && schema.readOnly?true:null"`
Setting the value to null if it doesn't exist, which would not set the …
> readOnly Update

- README.md
- projects/schema-form/src/lib/model/formproperty.ts
- src/app/json-schema-example/binding_sample_schema.json
Request for extending capabilities of `visibleIf` with simple `OR` and `AND` by using `oneOf` and `allOf`.
e.g. 
```
"visibleIf": {
"allOf": [
{
"forename": [
"$ANY$"
]
},
{
"name": [
"$ANY$"
]
}
]
}
```
and 
```
"visibleIf": {
"oneOf": [
{
"forename": [
"$ANY$"
]
},
{
"name": [
"$ANY$"
]
}
]
}
```
Backward compatible: You still can use the already known direct binding with the properties of `visibleIf` ...
... but maybe with should go further in future and remove the direct property binding in `visibleIf` completely and replace it with usual JSON object declaration.
This would bring the benefit of having properties like `maximum` and `minimum` and so on...
> exented visibleIf condition with `oneOf` and `allOf`

- README.md
- projects/schema-form/src/lib/form.component.ts
- projects/schema-form/src/lib/model/formproperty.ts
- projects/schema-form/src/lib/model/formpropertyfactory.ts
- projects/schema-form/src/lib/model/objectproperty.spec.ts
- projects/schema-form/src/lib/property-binding-registry.ts
- src/app/json-schema-example/json-schema-example.component.ts
- src/app/json-schema-example/visibility-binding-example-schema.json
... and not yet existing array-items or properties using a property-bindings-registry
This pull request addresses the issue named in #258 
The issue mainly points to the missing feature to address items that do not exists when the schema gets processed to create the from.
So this pull request implements a property-binding-registry where all path and targets from any not yet existing property's `visibileIf` bindings are store to.
When a property is added to a `formProperty` the visibility binding will be re-processed.
Enables visibility paths like 
```
/property1/array/1/name
/property1/array/*/name
/property1/array/*/item/*/name
/property1/array/*/item/1/name
```
> add support for visibility bindings on array type widgets

- projects/schema-form/src/lib/defaultwidgets/select/select.widget.ts
- src/app/json-schema-example/json-schema-example.component.ts
- src/app/json-schema-example/otherschema.json
Allow setting `enum` as options for the `select` widget
fixes #221
> Select support enum as option

- projects/schema-form/src/lib/defaultwidgets/array/array.widget.ts
in relation to the settings of 'maxItems' and 'minItems' in schema.
fixes #293
This is how it will set the buttons `disabled` or hide them:
Button **ADD** will be
- disabled if `maxItems` is reached
- hidden if `maxItems` equals `minItems` which means a fixed array length is only allowed
Button **REMOVE** will be
- disabled if `minItems` is reached
- hidden if `maxItems` equals `minItems` which means a fixed array length is only allowed
> hide or disable array widget add and remove button

- README.md
- package-lock.json
- package.json
- projects/schema-form/package.json
- projects/schema-form/src/lib/expression-compiler-factory.ts
- projects/schema-form/src/lib/form.component.ts
- projects/schema-form/src/lib/model/arrayproperty.ts
- projects/schema-form/src/lib/model/atomicproperties.spec.ts
- projects/schema-form/src/lib/model/formproperty.spec.ts
- projects/schema-form/src/lib/model/formproperty.ts
- projects/schema-form/src/lib/model/formpropertyfactory.ts
- projects/schema-form/src/lib/model/objectproperty.spec.ts
- projects/schema-form/src/lib/model/objectproperty.ts
- projects/schema-form/src/lib/schema-form.module.ts
- src/app/app.module.ts
- src/app/json-schema-example/visibility-binding-example-schema.json
VisibleIf condition supports now expressions.  
The execution is very sandboxed, since the context is not global and provided by the implementation.  
To make this request a non breaking change, the expression used must be initiated with the prefix `$EXP$`
e.g:  
```
"myField" : { // SOURCE
"visibleIf": {
"oneOf": [
{
"/person/1/age": // TARGET
[
"$EXP$ target.value < 18"
]
}
]
}
}
```
As expression parser and compiler **JEXL** is used.   
See it on git https://github.com/TomFrost/jexl .
> add support for expression in visibleIf condition #fixes 228

- package-lock.json
- package.json
Mainly the unused dependecy `@angular/http` has been removed from demo project.  
`@angular/http` is any also not available anymore in Angular 8.
> remove unused deprecated dependencies

- projects/schema-form/src/lib/defaultwidgets/radio/radio.widget.ts
- projects/schema-form/src/lib/defaultwidgets/select/select.widget.ts
add support state inactive for options of radio or select widget by setting the single option `"readOnly":true`
Example:
```json
{
"type": "object",
"properties": {
"radio": {
"type": "string",
"oneOf": [
{
"enum": [
"a"
]
},
{
"enum": [
"b"
],
"readOnly": true // option set inactive
},
{
"enum": [
"c"
]
}
]
},
"select": {
"type": "string",
"oneOf": [
{
"enum": [
"a"
]
},
{
"enum": [
"b"
],
"readOnly": true // option set inactive
},
{
"enum": [
"c"
]
}
]
}
}
```
_Won' t work when using `enum` only as options._
> add support state inactive for options of radio or select widget

- projects/schema-form/src/lib/model/ISchema.ts
- projects/schema-form/src/lib/model/index.ts
- projects/schema-form/src/public_api.ts
- src/app/json-schema-example/json-schema-example.component.ts
fix #340
Creating own UI Widget Library may requires extending of the actual schema definition with custom properties.
Since we are currently switching to Angular 9 now and our UI Widget Library makes excessive use of extending the schema we are really excited to see this published soon.
:-)
> allow custom properties in schema

- schema/ngx-schema-form-schema.json
- To validate against multiple sub-schemas,  they need to be defined in `allOf`.
- Given that `#/definitions/widgetTypeCustom` accepts any given string `#/definitions/widgetType` must use `anyOf` instead of `oneOf`
- Allow the use of numbers in `visibleIf`
> fix: ngx form json schema definition

- schema/ngx-schema-form-schema.json
* fix: ngx form json schema definition
* fix: widgetType json schema definition
* fix: allow the use of numbers in visibleIf
* feat: ensure that the custom widget id is not blank
> fix: ngx form json schema definition (#378)

- projects/schema-form/src/lib/model/formproperty.ts
Fix for #389 
Inconsistency when paths in visibleIf do not contain a leading `/`
> fix #389 Updates to vivibleIf's for oneOf and allOf

- projects/schema-form/src/lib/model/ISchema.ts
- projects/schema-form/src/lib/model/formproperty.ts
- projects/schema-form/src/lib/model/formpropertyfactory.ts
- projects/schema-form/src/lib/model/typemapping.ts
- projects/schema-form/src/lib/template-schema/field/field.ts
Solution based on proposal which is told in #397 with one exception, I limited possible use cases to one: currently allowed to use union type only with oneOf.
Another cases might ruin the widgets or might happen something an unpredictable at validation process or casting value or something else.
Allowed types to mixing in with null are "integer", "number", "string", "boolean".
> Add support of nullable union type for oneOf case

- package.json
There is no `cp` on windows `cmd`, which still seems to be the default for a `npm run` call. I added `ncp` as devDependencies and replaced `cp` in the `build:lib` command to make it os independent.
An alternative would be to make it with inline code like in the `copy:schema` script.
`get_version` with `cat`, `grep`, `awk` etc. is still problematic.
> Changed cp command in build:lib

- projects/schema-form/src/lib/defaultwidgets/checkbox/checkbox.widget.ts
- projects/schema-form/src/lib/defaultwidgets/radio/radio.widget.ts
- projects/schema-form/src/lib/defaultwidgets/range/range.widget.ts
- projects/schema-form/src/lib/defaultwidgets/select/select.widget.ts
- projects/schema-form/src/lib/defaultwidgets/string/string.widget.ts
In dev mode there is the famous warning about reactive forms and disable attribute
```
It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
you. We recommend using this approach to avoid 'changed after checked' errors.
Example:
form = new FormGroup({
first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
last: new FormControl('Drew', Validators.required)
});
```
I changed the widgets to use the already existing `DisableControlDirective`. The select widget had both methods: Attribute and via directive therefore I removed the attribute method.
> Use DisableControlDirective for widgets to remove warnings for reactive forms.

- projects/schema-form/src/lib/model/formproperty.ts
This is a fix for the issue #431 .
Because `value` can be the number `0` it will not correctly evaluate the expression and always returns false for the `visibleIf` because `!!value` for `0` is always false.
With this patch the `value` needs to be defined by checking `!!value` or it needs to be the number `0`.
> Fix for  #431

- README.md
- projects/schema-form/src/lib/model/formproperty.ts
- src/app/json-schema-example/json-schema-example.component.canonical-path.spec.ts
- src/app/json-schema-example/json-schema-example.component.ts
- src/app/json-schema-example/json-schema-example.component.visibleIf.spec.ts
- src/app/json-schema-example/visibility-binding-example-schema3.json
Added a chainable oneOf and allOf for the visibleIf property. Now, arbitrary boolean expressions can be written down. 2 tests were added and documentation is also modified.
All tests were successfully locally. So, I think that this is not a breaking change even I had to rewrite / rearrange a big part of `__bindVisibility_oneOf_or_allOf` method. I'm very unsure if the schema itself needs a modification.
For the record: I have a rather complex form, where just "or" or just "and" everything is not sufficient. I need expression like (a && b) || (a && c) etc. in the visibleIf. Therefore I implemented this patch.
> feat: Added chainable oneOf and allOf in visibleIf

- README.md
- projects/schema-form/src/lib/model/formproperty.ts
Once again a pull request by me.
I have no idea why this patch is working and I really like to discuss that because I don't like to blindly provide patches where I don't know why they are working.
In this reprox https://stackblitz.com/edit/angular-ivy-cxvsbz?file=src/app/app.component.ts click `Press to change` and see that the child object in `Non working` is not changed to `Desc. of child element 2` but in the second form in `Working` it is changed to `Desc. of child element 2`.
The non working schema uses `allOf` in `visibleIf` while the second just uses `visibleIf` **without** `allOf` or `oneOf`
It simply a one liner where I change from `subscribe` to `pipe` with `disctinctUntilChanged` within the binding function for `allOf` and `oneOf`. That's the same way as it is done when …
> Not working two-way data binding in corner cases

- CHANGELOG.md
- projects/schema-form/package.json
- projects/schema-form/src/lib/model/formproperty.ts
Let's take the following schema:
```
{
"$schema": "http://json-schema.org/draft-04/schema#",
"type": "object",
"title": "Root",
"properties": {
"firstLevel": {
"type": "object",
"title": "First Level",
"properties": {
"oneChildInteger": {
"type": "integer",
"default": 80,
"title": "Integer"
}
}
}
}
}
```
https://github.com/guillotinaweb/ngx-schema-form/blob/84d3f8b2573bc5fc3be2831c92b1a0bca97e1e2b/projects/schema-form/src/lib/model/formproperty.ts#L554-L572
1 Issue / Commit
For the root property of the schema `/` `_bindVisibilityRecursive` is called, which calls `forEachChildRecursive` with a function `fn`, where `fn` is simply calling `_bindVisibility` on each property.
For each child function `fn` is called and after that the check `if (child instanceof PropertyGroup) {` calls …
> Prevent multiple calls of _bindVisibility for the same elements when traversing the tree structure

- projects/schema-form/src/lib/form.component.ts
Due to `Object.assign` elements on root level like
this.model = 
```
{
"old": "foo"
}
```
and value =
```
{
"new": "bar"
}
```
gets merged to
```
{
"old": "foo",
"new": "bar"
}
```
but `old` is not visible anymore and should be removed from the model.
Assignment like `this.model = value` is also bad because this leads to bad behaviour with two-way data binding. I tried to use assignment with a change event to tell the parent that the child (`FormComponent`) has changed the model but because `FormComponent` implements `OnChanges` I had a loop.
Not the best fix but at least it just iterates through the keys at root level of the model and **not** into the nested structure.
> Remove invisible elements from model at root level

- projects/schema-form/src/lib/form.component.ts
- projects/schema-form/src/lib/model/formpropertyfactory.ts
First create the elements and then create initial bind of visibility by calling `_bindVisibility` just for the root element.
If you have many nested objects, this is a lot faster because each `PropertyGroup` does not call `_bindVisibility` at creation. Previously, it was called for each one at creation but eventually it will get called anyways because root element is a `PropertyGroup` which calls `_bindVisibility` of childs (and therefore for child `PropertyGroup`s).
> Bind visibility after creation to prevent multiple calls

- package.json
- projects/schema-form/src/lib/model/formproperty.ts
Using a multiple select widget as a condition for visibleIf only takes into account the first selection of a multiselct and not each element selected.
> Fix for multi select visibility conditional and rxjs versioning.

- README.md
Facing this issue when following the [getting started](https://github.com/guillotinaweb/ngx-schema-form#getting-started) and saw others are facing it as well #459 
I was able to build the app demo and noticed the [schema type is declared there](https://github.com/guillotinaweb/ngx-schema-form/blob/7e35e19e5e282b248c6fbeee6ab8c24f249dc623/src/app/json-schema-example/json-schema-example.component.ts#L29), so thinking this could be an omission?
---
Thanks for your work on this library! It is saving our team lots of time 🍻
> 🏷️ Add type for mySchema

- package-lock.json
- package.json
old version of rxjs is casuing peer dependency issues for angular 14 and above packages
> updating rxjs version

- projects/schema-form/src/lib/model/arrayproperty.ts
- src/app/json-schema-example/json-schema-example.component.canonical-path.spec.ts
- src/app/json-schema-example/json-schema-example.component.ts
- src/app/json-schema-example/json-schema-example.component.visibleIf.spec.ts
- src/app/json-schema-example/visibility-binding-example-schema4.json
Added sample as an example.
Added test of the sample.
> Fixing issue when using visibleIf in array items.
